### ISSUE TITLE
Can you provide Installation instructions?

### ISSUE THREAD

**Issue by planetahuevo** [gosmartsolutions/email-newsletters#1]
In case something is needed.

Thanks!

**Comment by mistylackie** [comment]
Yes, I am working on more detailed installation instruction. Hoping to have them published sometime this weekend.

**Comment by planetahuevo** [comment]
That would be great. So far I am reading the "a-beginners-guide-to-composer" links i found in google. 
Hard times to the mandrill users. :+1: 
Thanks again!

**Comment by planetahuevo** [comment]
I Think I have everyhing installed fine and composer is installed too, but I only have a 

```
Forbidden
You don't have permission to access / on this server.
```

When I try to access the root of my install. I also tried with a "composer install" just in case (following the tutorial, and it isntalled som other dependencies) but the frontpage has still the same message.  
Am I missing something?

**Comment by planetahuevo** [comment]
I do not know so much about composer, so maybe this is a stupid comment: 
Shouldn´t be any index.php or something on the root to load the app?

**Comment by mistylackie** [comment]
I added an index.html file to this project that has further details on how to install and run the program.
